### PR TITLE
Fix 'undefined' reference to linebreak when using streams

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by myndzi** [comment]
This breaks using mocha-unfunk-reporter with node streams, a merge would be appreciated.

**Comment by Bartvds** [comment]
My bad; I'm sorry this got burried. I'll push asap.

**Comment by myndzi** [comment]
Thanks! _Checks another fork off the list_

**Comment by myndzi** [comment]
P.S. May want to version bump and update the dependency in mocha-unfunk-reporter

**Comment by Bartvds** [comment]
Well, it was a bugfix so I pushed it as a patch release: I checked mocha-unfunk-reporter so it'll show-up automatically.

**Comment by myndzi** [comment]
Yeah, I meant bump the patch version :) Thanks.

**Pull request merged**
